version: '3.5'

services:

  php-fpm:
    container_name: docker-php-fpm-example-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html:rw
      - ~/.composer:/root/.composer/cache

  certbot:
    # restart: unless-stopped #+++
    image: certbot/certbot
    container_name: certbot
    volumes:
      #cerbot
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
      - ./data/logs/letsencrypt:/var/log/letsencrypt:rw
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Проверяет каждые 12 часов, нужны ли новые сертификаты
    # command: certonly --webroot --webroot-path=/var/www/certbot --email msbios@gmail.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com

  nginx:
    # restart: unless-stopped
    # Перезапустит контейнер в непредвиденных ситуациях
    container_name: docker-nginx-example-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html:rw
      - ./data/logs/nginx:/var/log/nginx:rw

      #cerbot
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    depends_on:
      - certbot
      - php-fpm
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть

#volumes:
#  certbot-etc:
#  certbot-var:
#  certbot-web: